server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/productos {
    proxy_pass http://producto-service:3001/productos;
  }

  location /api/carrito {
    proxy_pass http://carrito-service:3002/carrito;
  }

  location /api/contacto {
    proxy_pass http://contacto-service:3003/contacto;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
