server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/movies/ {
    proxy_pass http://movies-service:3000/movies/;
  }

  location = /api/movies {
    proxy_pass http://movies-service:3000/movies;
  }

  location /api/showtimes/ {
    proxy_pass http://showtimes-service:3000/showtimes/;
  }

  location = /api/showtimes {
    proxy_pass http://showtimes-service:3000/showtimes;
  }

  location /api/seats/availability/ {
    proxy_pass http://seats-service:3000/availability/;
  }

  location /api/seats/reservations {
    proxy_pass http://seats-service:3000/reservations;
  }

  location /api/purchases/coupons/ {
    proxy_pass http://purchases-service:3000/coupons/;
  }

  location /api/purchases/ {
    proxy_pass http://purchases-service:3000/purchases/;
  }

  location = /api/purchases {
    proxy_pass http://purchases-service:3000/purchases;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
